services:
  jenkins:
    image: jenkins/jenkins:lts  # Use the latest LTS version of Jenkins
    ports:
      - "8080:8080"               # Expose Jenkins on port 8080
      - "50000:50000"             # Expose Jenkins agent port
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"  # Optional: Set a prefix if running behind a reverse proxy
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use the host Docker daemon
    networks:
      - jenkins-net

  dind:
    image: docker:latest  # Use the latest Docker image
    privileged: true       # Required to run Docker-in-Docker
    volumes:
      - /var/lib/docker     # Persist Docker data
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_home:

