services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use host Docker
    networks:
      - jenkins-network

  docker:
    image: docker:20.10.23-dind  # Update to the latest DinD image
    privileged: true  # Required for DinD
    volumes:
      - docker-data:/var/lib/docker  # Persist Docker data
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  docker-data:

networks:
  jenkins-network:

