version: '3.8'  # Specify the version of Docker Compose

networks:
  docker:

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins:
    image: jenkins:alpine
    restart: always
    networks:
      - docker
    ports:
      - 8080:8080  # Jenkins UI
      - 50000:50000  # Jenkins agent communication
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro  # Read-only access to certs
      - $HOME:/home  # Mount home directory
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    image: docker:dind
    privileged: true  # Required for DinD to function
    restart: always
    networks:
      docker:
        aliases: 
          - docker
    ports:
      - 2376:2376  # Docker daemon port
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client  # Ensure certs are accessible
      - $HOME:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs  # Set TLS cert directory

